spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
telegrambots:
  enabled: true
telegram:
  bot:
    name: name
    token: token
